# Generated by Django 4.2.8 on 2024-02-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appMy', '0002_alter_category_titles_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Resim'),
        ),
    ]
